name: build

on:
  push:
    branches: ['main']
  pull_request: ~
  workflow_dispatch: ~

jobs:
  test:
    runs-on: [solinas]

    strategy:
      fail-fast: false
      matrix:
        node-version: ${{ fromJSON(vars.SUPPORTED_NODE_VERSIONS) }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: ${{ vars.PNPM_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - run: pnpm test
      - run: pnpm test:type

  checks:
    runs-on: [solinas]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ vars.PNPM_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.DEFAULT_NODE_VERSION }}
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      # - run: pnpm build # might be needed in the future
      - run: pnpm lint

  build:
    runs-on: [solinas]
    needs: [test, checks]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ vars.PNPM_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.DEFAULT_NODE_VERSION }}
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - run: pnpm compile
