name: lint pr

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  lint-pr:
    runs-on: [solinas]
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GANDALF_PAT }}
        with:
          subjectPattern: ^(?![A-Z]).+$ # no uppercase letters at the beginning
